export const OPTIONS = [
  "All",
  "Today",
  "Tomorrow",
  "Yesterday",
  "This month",
  "Next month",
];

export const WARN_MSG =
  "Data is retained exclusively for the duration of the current session.";

export const INPUT_FORM_DATA = {
  name: "",
  email: "",
  dob: null,
  phoneNo: null,
};
export const DATA = [
  {
    id: "C1",
    name: "Zendaya",
    age: 27,
    dob: "1996-09-01",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: "C2",
    name: "Timothée Chalamet",
    age: 28,
    dob: "1995-12-27",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: "C3",
    name: "Emma Watson",
    age: 34,
    dob: "1990-04-15",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: "C4",
    name: "Tom Holland",
    age: 28,
    dob: "1996-06-01",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: "C5",
    name: "Ariana Grande",
    age: 31,
    dob: "1993-06-26",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "C6",
    name: "Chris Evans",
    age: 43,
    dob: "1981-06-13",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: "C7",
    name: "Taylor Swift",
    age: 35,
    dob: "1989-12-13",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: "C8",
    name: "Robert Pattinson",
    age: 38,
    dob: "1986-05-13",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: "C9",
    name: "Selena Gomez",
    age: 32,
    dob: "1992-07-22",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    id: "C10",
    name: "Dylan O'Brien",
    age: 33,
    dob: "1991-08-26",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    id: "C11",
    name: "Natalie Portman",
    age: 43,
    dob: "1981-06-09",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    id: "C12",
    name: "Ryan Reynolds",
    age: 48,
    dob: "1976-10-23",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: "C13",
    name: "Florence Pugh",
    age: 29,
    dob: "1996-01-03",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: "C14",
    name: "Millie Bobby Brown",
    age: 21,
    dob: "2004-02-19",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: "C15",
    name: "Finn Wolfhard",
    age: 22,
    dob: "2002-12-23",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  },
  {
    id: "C16",
    name: "Gal Gadot",
    age: 40,
    dob: "1985-04-30",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/48.jpg",
  },
  {
    id: "C17",
    name: "Jake Gyllenhaal",
    age: 44,
    dob: "1980-12-19",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/38.jpg",
  },
  {
    id: "C18",
    name: "Margot Robbie",
    age: 35,
    dob: "1990-07-02",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "C19",
    name: "Henry Cavill",
    age: 42,
    dob: "1983-05-05",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: "C20",
    name: "Hailee Steinfeld",
    age: 28,
    dob: "1996-12-11",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: "C21",
    name: "Noah Centineo",
    age: 28,
    dob: "1996-05-09",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: "C22",
    name: "Saoirse Ronan",
    age: 31,
    dob: "1994-04-12",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    id: "C23",
    name: "Joe Keery",
    age: 33,
    dob: "1992-04-24",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: "C24",
    name: "Lily Collins",
    age: 36,
    dob: "1989-03-18",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/36.jpg",
  },
  {
    id: "C25",
    name: "Logan Lerman",
    age: 33,
    dob: "1992-01-19",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: "C26",
    name: "Tomer Hanks",
    age: 33,
    dob: "1992-05-02",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: "C27",
    name: "Logan Bail Lerman",
    age: 34,
    dob: "1991-05-01",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: "C28",
    name: "Bail Timmy",
    age: 34,
    dob: "1991-05-03",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
];
