import { createContext, useContext } from "react";
import {
  Bell,
  ChevronDown,
  ChevronUp,
  Download,
  Edit2,
  FileMinus,
  FilePlus,
  Frown,
  Linkedin,
  Mail,
  Phone,
  Search,
  Star,
  Trash,
  UserPlus,
  X,
} from "react-feather";

export const SessionContext = createContext();

export const useSession = () => useContext(SessionContext);

export const FeatherIcons = {
  star: Star,
  user: UserPlus,
  download: Download,
  mail: Mail,
  phone: Phone,
  frown: Frown,
  linkedIn: Linkedin,
  close: X,
  bell: Bell,
  chevron_up: ChevronUp,
  chevron_down: ChevronDown,
  file_plus:FilePlus,
  file_minus:FileMinus,
  edit:Edit2,
  trash: Trash,
  search: Search
};

export const DROPDOWN_OPTIONS = [
  "All",
  "Today",
  "Tomorrow",
  "Yesterday",
  "This month",
  "Next month",
];

export const INPUT_FORM_DATA = {
  id: "",
  name: "",
  email: "",
  dob: undefined,
  phoneNo: undefined,
  relationship: "",
  image: "",
};

export const INITIAL_REDUCER_DATA = {
  dataSource: [],
  list: [],
  showContent: [],
  selected: DROPDOWN_OPTIONS[0],
  memberDetails:{}
};

export const REDUCER_DATA = {
  DATA_SOURCE: "set_data_source",
  LIST: "set_list",
  SHOW_CONTENT: "set_show_content",
  SELECTED: "set_selected",
  MEMBER_DETAIL:'set_member_details'
};

export const PROFILE_PIC_TEXT = {
  NEW: "Choose Profile Pic",
  RENAME: "Replace Profile Pic",
};

export const DATE_TYPE = {
  MM: "MM",
  MMDD: "MM-DD",
  DDMMMYYYY: "DD MMM YYYY",
  DAY: "day",
  MONTH: "month",
};

export const DATA = [
  {
    id: "Sample1",
    name: "Zendaya",
    age: 27,
    dob: "1996-09-01",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: "Sample2",
    name: "Timothée Chalamet",
    age: 28,
    dob: "1995-12-27",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: "Sample3",
    name: "Emma Watson",
    age: 34,
    dob: "1990-04-15",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: "Sample4",
    name: "Tom Holland",
    age: 28,
    dob: "1996-06-01",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: "Sample5",
    name: "Ariana Grande",
    age: 31,
    dob: "1993-06-26",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: "Sample6",
    name: "Chris Evans",
    age: 43,
    dob: "1981-06-13",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: "Sample7",
    name: "Taylor Swift",
    age: 35,
    dob: "1989-12-13",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: "Sample8",
    name: "Robert Pattinson",
    age: 38,
    dob: "1986-05-13",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: "Sample9",
    name: "Selena Gomez",
    age: 32,
    dob: "1992-07-22",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    id: "Sample10",
    name: "Dylan O'Brien",
    age: 33,
    dob: "1991-08-26",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    id: "Sample11",
    name: "Natalie Portman",
    age: 43,
    dob: "1981-06-09",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    id: "Sample12",
    name: "Ryan Reynolds",
    age: 48,
    dob: "1976-10-23",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: "Sample13",
    name: "Florence Pugh",
    age: 29,
    dob: "1996-01-03",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: "Sample14",
    name: "Millie Bobby Brown",
    age: 21,
    dob: "2004-02-19",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: "Sample15",
    name: "Finn Wolfhard",
    age: 22,
    dob: "2002-12-23",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  },
  {
    id: "Sample16",
    name: "Gal Gadot",
    age: 40,
    dob: "1985-04-30",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/48.jpg",
  },
  {
    id: "Sample17",
    name: "Jake Gyllenhaal",
    age: 44,
    dob: "1980-12-19",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/38.jpg",
  },
  {
    id: "Sample18",
    name: "Margot Robbie",
    age: 35,
    dob: "1990-07-02",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "Sample19",
    name: "Henry Cavill",
    age: 42,
    dob: "1983-05-05",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: "Sample20",
    name: "Hailee Steinfeld",
    age: 28,
    dob: "1996-12-11",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: "Sample21",
    name: "Noah Centineo",
    age: 28,
    dob: "1996-05-09",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: "Sample22",
    name: "Saoirse Ronan",
    age: 31,
    dob: "1994-04-12",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    id: "Sample23",
    name: "Joe Keery",
    age: 33,
    dob: "1992-04-24",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: "Sample24",
    name: "Lily Collins",
    age: 36,
    dob: "1989-03-18",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/women/36.jpg",
  },
  {
    id: "Sample25",
    name: "Logan Lerman",
    age: 33,
    dob: "1992-01-19",
    relation: "Celebrity",
    email: null,
    phoneNo: null,
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];

export const FEEDBACK = {
  MSG1: "Whether you enjoyed the app or see room for improvement, your input truly matters. Feel free to reach out via ",
  MSG2: "I'd love to hear from you. Thanks so much for checking it out!",
  MAIL: "mailto:prathee024@email.com",
  LINKEDIN: "https://www.linkedin.com/in/pratheeksha-poonja-4a62a9bb/",
};

export const RELATION_TYPE = [
  "Family",
  "Friend",
  "Colleague",
  "Classmate",
  "Neighbor",
  "Partner",
  "Spouse",
  "Parent",
  "Sibling",
  "Child",
  "Relative",
  "Acquaintance",
  "Celebrity",
  "Mentor",
  "Boss",
  "Client",
  "Others",
];

export const MESSAGES = {
  NO_BDAY_TONIGHT: "No candles to blow out ",
  BDAY_WISH: "Send birthday vibes",
  BELATED_WISH: "Send belated birthday wishes",
  FEEDBACK: "Share Your Thoughts",
  DROPDOWM_MSG: "Who's Celebrating Soon?:",
  CELEBRATE: "It's celebration time!",
  LINKEDIN_CONNECT: "Connect with me on LinkedIn",
  MAIL_CONNECT: "Get in touch via email",
  ADD_CONTACTS: "Add Contacts",
  LOAD_SAMPLE_DATA: "Load Sample Data",
  REMOVE_SAMPLE_DATA: "Remove Sample Data",
  WARN_MSG:
    "Data is retained exclusively for the duration of the current session.",
  ERR_NAME: "! Minimum of 3 characters",
  ERR_MAIL: "! Invalid email ID",
  ERR_DOB: "! Invalid date of birth",
  ERR_PHONENO: "! Right format: 123-456-7890",
  CELEBRATE_MSG: "It's Your Special Day - Celebrate Big!",
  BIRTHDAY_WISHES:
    "Wishing you a very happy birthday today! May your day be filled with love, laughter, and all the things that make you smile. Cheers to another amazing year!",
  BELATED_WISHES:
    "Better late than never! Wishing you all the joy and success you deserve this year. Happy belated birthday!",
  ADVANCE_WISHES:
    "I'm sending you my best wishes ahead of time because I want you to have the best celebration before it even starts. I hope your year ahead is as spectacular as you!",
};

export const BIRTHDAY_TIME = {
  TODAY: "Today",
  BELATED: "Belated",
  Advanced: "Advanced",
};
