export const OPTIONS = ["All", "Today", "Tomorrow", "This month", "Next month"];

export const DATA = [
  {
    id: 1,
    name: "Zendaya",
    age: 27,
    dob: "1996-09-01",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 2,
    name: "Timothée Chalamet",
    age: 28,
    dob: "1995-12-27",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: 3,
    name: "Emma Watson",
    age: 34,
    dob: "1990-04-15",
    image: "https://randomuser.me/api/portraits/women/55.jpg",
  },
  {
    id: 4,
    name: "Tom Holland",
    age: 28,
    dob: "1996-06-01",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
  },
  {
    id: 5,
    name: "Ariana Grande",
    age: 31,
    dob: "1993-06-26",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 6,
    name: "Chris Evans",
    age: 43,
    dob: "1981-06-13",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: 7,
    name: "Taylor Swift",
    age: 35,
    dob: "1989-12-13",
    image: "https://randomuser.me/api/portraits/women/40.jpg",
  },
  {
    id: 8,
    name: "Robert Pattinson",
    age: 38,
    dob: "1986-05-13",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 9,
    name: "Selena Gomez",
    age: 32,
    dob: "1992-07-22",
    image: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    id: 10,
    name: "Dylan O’Brien",
    age: 33,
    dob: "1991-08-26",
    image: "https://randomuser.me/api/portraits/men/30.jpg",
  },
  {
    id: 11,
    name: "Natalie Portman",
    age: 43,
    dob: "1981-06-09",
    image: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    id: 12,
    name: "Ryan Reynolds",
    age: 48,
    dob: "1976-10-23",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 13,
    name: "Florence Pugh",
    age: 29,
    dob: "1996-01-03",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 14,
    name: "Millie Bobby Brown",
    age: 21,
    dob: "2004-02-19",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: 15,
    name: "Finn Wolfhard",
    age: 22,
    dob: "2002-12-23",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  },
  {
    id: 16,
    name: "Gal Gadot",
    age: 40,
    dob: "1985-04-30",
    image: "https://randomuser.me/api/portraits/women/48.jpg",
  },
  {
    id: 17,
    name: "Jake Gyllenhaal",
    age: 44,
    dob: "1980-12-19",
    image: "https://randomuser.me/api/portraits/men/38.jpg",
  },
  {
    id: 18,
    name: "Margot Robbie",
    age: 35,
    dob: "1990-07-02",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 19,
    name: "Henry Cavill",
    age: 42,
    dob: "1983-05-05",
    image: "https://randomuser.me/api/portraits/men/39.jpg",
  },
  {
    id: 20,
    name: "Hailee Steinfeld",
    age: 28,
    dob: "1996-12-11",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: 21,
    name: "Noah Centineo",
    age: 28,
    dob: "1996-05-09",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 22,
    name: "Saoirse Ronan",
    age: 31,
    dob: "1994-04-12",
    image: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    id: 23,
    name: "Joe Keery",
    age: 33,
    dob: "1992-04-24",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 24,
    name: "Lily Collins",
    age: 36,
    dob: "1989-03-18",
    image: "https://randomuser.me/api/portraits/women/36.jpg",
  },
  {
    id: 25,
    name: "Logan Lerman",
    age: 33,
    dob: "1992-01-19",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 26,
    name: "Tomer Hanks",
    age: 33,
    dob: "1992-05-01",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 27,
    name: "Logan Bail Lerman",
    age: 34,
    dob: "1991-05-02",
    image: "https://randomuser.me/api/portraits/men/17.jpg",
  },
];
